
before:
  hooks:
    - make -C runtimes/cloudformation clean kilt.zip
    - make -C installer deps
    - go install github.com/markbates/pkger/cmd/pkger@latest
    - go generate installer/generate.go
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/kilt-installer
    dir: installer
    binary: kilt
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: macos
      linux: linux
      windows: windows
      386: x86
      amd64: x86_64
    name_template: "kilt-installer-{{ .Os }}-{{ .Arch }}"
    format: binary
release:
  extra_files:
    - glob: ./runtimes/cloudformation/kilt.zip

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
