AWSTemplateFormatVersion: 2010-09-09
Description: Macro kilt-{{ .MacroName }} deployment
Resources:
  KiltRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
              - Effect: Allow
                Action: "s3:*"
                Resource: "arn:aws:s3:::{{ .BucketName }}/*"
  KiltLambda{{ .MacroName }}:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: go1.x
      Handler: handler
      Role:
        Fn::GetAtt:
          - KiltRole
          - Arn
      Environment:
        Variables:
          KILT_DEFINITION_TYPE: s3
          KILT_DEFINITION: "{{ .BucketName }}/{{ .MacroFileName }}"
          {{if .OptIn -}}
          KILT_OPT_IN: "YES"
          {{- end}}
          {{if .KiltKmsSecret -}}
          KILT_IMAGE_AUTH_SECRET: "{{ .KiltKmsSecret }}"
          {{- end}}
      Code:
        S3Bucket: {{ .BucketName }}
        S3Key: {{ .KiltZipPath }}

  KiltMacro:
    Type: AWS::CloudFormation::Macro
    Properties:
      Name: {{ .MacroName }}
      Description: Kilt - Applies kilt patching in s3://{{ .BucketName }}/{{ .MacroFileName }} to fargate tasks
      FunctionName:
        Fn::GetAtt:
          - KiltLambda{{ .MacroName }}
          - Arn
