name: Quality Gate

on:
  pull_request:
    branches: [ master ]

jobs:
  test-cfn-runtime:
    name: CFN Runtime
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.20
        id: go

      - name: Check out code
        uses: actions/checkout@v4

      - name: Test
        run: |
          cd runtimes/cloudformation
          go test -v ./...

  test-kilt-lib:
    name: Kilt Lib
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.20
        id: go

      - name: Check out code
        uses: actions/checkout@v4

      - name: Test
        run: |
          cd pkg
          go test -v ./...
