name: Release Kilt Runtimes

on:
  push:
    branches: [ master ]

jobs:
  build-utilities:
    runs-on: ubuntu-latest
    name: Create and push docker image of utilities to GitHub Packages
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./utilities/
          file: ./utilities/Dockerfile
          platforms: linux/amd64
          push: true
          tags: docker.pkg.github.com/falcosecurity/kilt/utilities:latest