name: CFN Runtime Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go
      - uses: actions/checkout@v2
        name: Check out code

      - name: Test
        run: |
          cd runtimes/cloudformation
          go test -v ./...